"use client";

import { useEffect, useMemo, useState } from "react";
import { PlannerForm } from "@/components/PlannerForm";
import { PlannerInput, TravelPlan } from "@/lib/types";

const defaultInput: PlannerInput = {
  destination: "",
  days: 3,
  budgetTier: "medium",
  mode: "balanced"
};

const formatMoney = (amount: number) => `$${amount.toLocaleString()}`;

const printAsPdf = () => {
  window.print();
};

export default function HomePage() {
  const [input, setInput] = useState<PlannerInput>(defaultInput);
  const [plan, setPlan] = useState<TravelPlan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<"ai" | "fallback" | null>(null);

  useEffect(() => {
    const stored = sessionStorage.getItem("trip-input");
    if (stored) {
      try {
        setInput(JSON.parse(stored) as PlannerInput);
      } catch {
        sessionStorage.removeItem("trip-input");
      }
    }
  }, []);

  const totalBudget = useMemo(() => {
    if (!plan) return 0;
    return (
      plan.budgetBreakdown.transport +
      plan.budgetBreakdown.stay +
      plan.budgetBreakdown.food +
      plan.budgetBreakdown.activities
    );
  }, [plan]);
  const safeTotalBudget = totalBudget || 1;

  const generatePlan = async (values: PlannerInput) => {
    setLoading(true);
    setError(null);
    setInput(values);
    sessionStorage.setItem("trip-input", JSON.stringify(values));

    try {
      const response = await fetch("/api/plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(values)
      });

      if (!response.ok) {
        throw new Error("Could not generate plan.");
      }

      const data = (await response.json()) as { plan: TravelPlan; source: "ai" | "fallback" };
      setPlan(data.plan);
      setSource(data.source);
    } catch {
      setError("Something went wrong while generating your trip plan.");
      setPlan(null);
      setSource(null);
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="page">
      <div className="aurora" />
      <section className="hero">
        <p className="eyebrow">AI TRAVEL CONCIERGE</p>
        <h1>Plan your whole trip in one beautiful screen.</h1>
        <p className="sub">
          Pick destination, days, and budget. Get transport, stays, food, and a day-by-day
          itinerary in seconds.
        </p>
        <PlannerForm initialValues={input} onSubmit={generatePlan} loading={loading} />
      </section>

      {error && <p className="error">{error}</p>}

      {plan && (
        <section className="results" id="itinerary-print-area">
          <div className="results-head">
            <div>
              <h2>{input.destination} trip blueprint</h2>
              <p>{plan.overview}</p>
              <small className="source-tag">
                Generated by: {source === "ai" ? "AI API" : "Local fallback planner"}
              </small>
            </div>
            <button className="print-btn" onClick={printAsPdf}>
              Download Itinerary (PDF)
            </button>
          </div>

          <div className="grid two">
            <article className="card lift">
              <h3>Transport Recommendation</h3>
              <p>
                <strong>{plan.transport.mode}</strong> · {plan.transport.duration}
              </p>
              <p>Approx cost: {plan.transport.approximateCost}</p>
              <p>{plan.transport.reason}</p>
            </article>

            <article className="card lift">
              <h3>Weather Snapshot</h3>
              <p>{plan.weather.condition}</p>
              <p>Avg Temp: {plan.weather.avgTempC}°C</p>
              <p>{plan.weather.note}</p>
            </article>
          </div>

          <article className="card">
            <h3>Budget Breakdown</h3>
            <p className="budget-total">Estimated Total: {formatMoney(totalBudget)}</p>
            <div className="bars">
              {(
                [
                  ["Transport", plan.budgetBreakdown.transport],
                  ["Stay", plan.budgetBreakdown.stay],
                  ["Food", plan.budgetBreakdown.food],
                  ["Activities", plan.budgetBreakdown.activities]
                ] as [string, number][]
              ).map(([label, value]) => (
                <div className="bar-row" key={label}>
                  <div className="bar-label">
                    <span>{label}</span>
                    <span>{formatMoney(value)}</span>
                  </div>
                  <div className="bar-track">
                    <div
                      className="bar-fill"
                      style={{ width: `${Math.max((value / safeTotalBudget) * 100, 4)}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </article>

          <div className="grid two">
            <article className="card">
              <h3>Hotel Recommendations</h3>
              <div className="stack">
                {plan.hotels.map((hotel) => (
                  <div key={hotel.name} className="mini-card">
                    <h4>{hotel.name}</h4>
                    <p>{hotel.locationAdvantage}</p>
                    <p>
                      {hotel.pricePerNight} per night · {hotel.rating}
                    </p>
                    <p>{hotel.distanceFromAttractions} from major attractions</p>
                  </div>
                ))}
              </div>
            </article>

            <article className="card">
              <h3>Restaurant Picks</h3>
              <div className="stack">
                {plan.restaurants.map((restaurant) => (
                  <div key={restaurant.name} className="mini-card">
                    <h4>{restaurant.name}</h4>
                    <p>
                      Veg: {restaurant.vegOptions} | Non-veg: {restaurant.nonVegOptions}
                    </p>
                    <p>Try: {restaurant.localFamousDishes}</p>
                    <p>Meal cost: {restaurant.estimatedCostPerMeal}</p>
                  </div>
                ))}
              </div>
            </article>
          </div>

          <article className="card">
            <h3>Day-wise Itinerary</h3>
            <div className="timeline">
              {plan.itinerary.map((day) => (
                <div key={day.day} className="day-item">
                  <h4>
                    Day {day.day}: {day.title}
                  </h4>
                  <p>Suggested timing: {day.suggestedTimings}</p>
                  <p>Must-visit: {day.mustVisitPlaces.join(", ")}</p>
                  <p>Food nearby: {day.nearbyFoodSpots.join(", ")}</p>
                </div>
              ))}
            </div>
          </article>
        </section>
      )}
    </main>
  );
}
